apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    type: web
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/init

---

apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  selector:
    type: web   # 라벨로 선택
  ports:
  - port: 8080  # 포트